module TwoRingToolError 
	INVALID_CHANGELOG_PATH = 65
	UNFORCED_ANNOTATION_OVERWRITE_ATTEMPT = 66
	CHANGELOG_ENTRY_NOT_FOUND = 67
	GIT_DIRTY_INDEX = 68
	PODSPEC_PUSH_FAILED = 69
	INVALID_SEMVER_COMPONENT = 70
end